[package]
name = "myothercrate"
version = "0.1.0"
authors = ["sharks"]

[dependencies]
flame = {version = "0.2.2", optional = true}
flamer = {version = "^0.2.1", optional = true}

[features]
default = []
flame_it = ["flame", "flamer"]
